#!/bin/bash

a=32
b=$(expr $a \* 32)
r=251
for i in {1..9}
do
    for j in {1..3}
    do
        ./pqrandom $0.$a.$j $r $a $b 1 1024 0 0 1
        r=$(expr 1 + $r)
    done
    a=$(expr 2 \* $a)
    b=$(expr 2 \* $b)
done
