CC 		=	gcc
FLAGS 	=	-Wall -g -pg -std=c99 -O2

heaps: 
	$(CC) $(FLAGS) -c binary_array_heap.c -o binary_array_heap.o
	$(CC) $(FLAGS) -c binary_pointer_heap.c -o binary_pointer_heap.o
	$(CC) $(FLAGS) -c fibonacci_heap.c -o fibonacci_heap.o
	$(CC) $(FLAGS) -c heap_common.c -o heap_common.o
	$(CC) $(FLAGS) -c pairing_heap.c -o pairing_heap.o
	$(CC) $(FLAGS) -c quake_heap.c -o quake_heap.o
	$(CC) $(FLAGS) -c rank_pairing_heap.c -o rank_pairing_heap.o
	$(CC) $(FLAGS) -c violation_heap.c -o violation_heap.o

