#!/bin/bash

a=512
r=39000
for i in {1..11}
do
    for j in {1..3}
    do
        ./spbad $a 10 -s$r | ../splib_pq/bin/dikh spbad_sparse.$a.$j
        r=$(expr 1 + $r)
    done
    a=$(expr 2 \* $a)
done
