#!/bin/bash

a=512
b=256
r=39000
for i in {1..6}
do
    for j in {1..3}
    do
        ./spbad $a $b -s$r | ../splib_pq/bin/dikh spbad_dense.$a.$j
        r=$(expr 1 + $r)
    done
    a=$(expr 2 \* $a)
    b=$(expr 2 \* $b)
done

