#!/bin/bash
#Modified from original for DIMACS Challenge 5 ccm 7/96
#

a=1024
b=16384
r=251
for i in {1..13}
do
    for j in {1..3}
    do
        ../bin/spacyc $a $b $r -cl1 | ../bin/dikh ../results/$0.$a.$j
        r=$(expr 1 + $r)
    done
    a=$(expr 2 \* $a)
    b=$(expr 2 \* $b)
done

