#!/bin/bash
#Modified from original for DIMACS Challenge 5 ccm 7/96
#

a=64
r=251
for i in {1..7}
do
    for j in {1..3}
    do
        ../bin/spgrid $a $a $r -cl10000 | ../bin/dikh ../results/$0.$a.$j
        r=$(expr 1 + $r)
    done
    a=$(expr 2 \* $a)
done
