#!/bin/bash
#Modified from original for DIMACS Challenge 5  ccm 7/96
#

a=256
r=251
for i in {1..11}
do
    for j in {1..3}
    do
        ../bin/spgrid $a 32 $r -cc -cl1 -cm1 -ax64 -ix5 -ih5 -in0 -is1 | ../bin/dikh ../results/$0.$a.$j
        r=$(expr 1 + $r)
    done
    a=$(expr 2 \* $a)
done

