#!/bin/bash

a=64
r=251
for i in {1..8}
do
    for j in {1..3}
    do
        ../bin/spgrid $a $a $r -cl10000 -s | ../bin/dikh ../results/$0.$a.$j
        r=$(expr 1 + $r)
    done
    a=$(expr 2 \* $a)
done
