#!/bin/bash
#Modified from oridinal for DIMACS Challenge 5 ccm 7/96
#

a=8192
b=32768
r=1024
for i in {1..10}
do
    for j in {1..3}
    do
        ../bin/sprand $a $b $r -cl1 | ../bin/dikh ../results/$0.$a.$j
        r=$(expr 1 + $r)
    done
    a=$(expr 2 \* $a)
    b=$(expr 2 \* $b)
done
