#!/bin/bash

a=512
b=65536
r=11111
for i in {1..10}
do
    for j in {1..3}
    do
        ../bin/sprand $a $b $r -cl1 | ../bin/dikh ../results/$0.$a.$j
        r=$(expr 1 + $r)
    done
    a=$(expr 2 \* $a)
    b=$(expr 2 \* $b)
done

