#!/bin/bash

a=1024
b=16384
r=111111
for i in {1..14}
do
    for j in {1..3}
    do
        ../bin/spacyc $a $b $r -cl1 | ../bin/dikh ../results/$0.$a.$j
        r=$(expr 1 + $r)
    done
    a=$(expr 2 \* $a)
    b=$(expr 2 \* $b)
done

